{% set version = "2.2.2" %}

package:
  name: triqs
  version: {{ version }}

source:
  url: https://github.com/TRIQS/triqs/releases/download/{{ version }}/triqs-{{ version }}.tar.gz
  sha256: b7fc1f22aca3dc8f353c3aee416c20d1d4991d42b008b257d0290690da39d5ad

build:
  number: 1
  skip: True  # [win or py>30]
  merge_build_host: True

requirements:
  build:
    - cmake
    - make
    - clangxx >=8  # [osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - fftw
    - gmp
    - hdf5
    - h5py
    - mako
    - mpi4py
    - numpy  1.14
    - {{ mpi }}
    - python
    - scipy
    - libblas
    - liblapack
    - libclang
    - zlib
  run:
    - fftw
    - gmp
    - hdf5
    - h5py
    - mako
    - mpi4py
    - {{ pin_compatible("numpy") }}
    - {{ mpi }}
    - python
    - scipy
    - matplotlib-base
    - libclang
    - zlib
    - {{ compiler('cxx') }}

test:
  imports:
    - pytriqs

about:
  home: https://triqs.github.io
  license: GPLv3
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Toolbox for Research on Interacting Quantum Systems'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
